# Generated by Django 5.2.5 on 2025-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='planoalimentar',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='planoalimentar',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='plano',
        ),
        migrations.AddField(
            model_name='consulta',
            name='tmb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='MedidaCorporal',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='PlanoAlimentar',
        ),
        migrations.DeleteModel(
            name='Refeicao',
        ),
    ]
