# Generated by Django 5.2.5 on 2025-08-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_remove_pagamento_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor'),
        ),
    ]
