# Generated by Django 5.2.5 on 2025-08-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0003_consulta_valor_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
