# Generated by Django 5.2.5 on 2025-08-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0004_remove_consulta_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='consulta_feita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateTimeField(),
        ),
    ]
