# Generated by Django 5.2.5 on 2025-08-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0005_consulta_consulta_feita_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='consulta_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornos', to='nutri.consulta'),
        ),
    ]
