# Generated by Django 5.2.5 on 2025-08-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0007_remove_consulta_consulta_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
