# Generated by Django 5.2.5 on 2025-08-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0008_paciente_informacoes_adicionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Peito')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Abdomen')),
                ('iliaca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Ilíaca')),
                ('axilar_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Axiliar Média')),
                ('coxas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Coxas')),
                ('triceps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Tríceps')),
                ('escapula', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medida Escápula')),
                ('circunf_peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Peitoral')),
                ('circunf_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Cintura')),
                ('circunf_abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Abdomen')),
                ('circunf_biceps_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Bíceps (Dir.)')),
                ('circunf_biceps_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Bíceps (Esq.)')),
                ('circunf_antebraco_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Antebraço (Dir.)')),
                ('circunf_antebraco_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Antebraço (Esq.)')),
                ('circunf_quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Quadril')),
                ('circunf_coxa_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Coxa (Dir.)')),
                ('circunf_coxa_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Coxa (Esq.)')),
                ('circunf_pant_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Panturrilha (Dir.)')),
                ('circunf_pant_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Circunf Panturrilha (Esq.)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consulta_avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='nutri.consulta')),
            ],
        ),
    ]
