# Generated by Django 5.2.5 on 2025-08-25 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0009_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='consulta_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='nutri.consulta'),
        ),
    ]
