# Generated by Django 5.2.5 on 2025-08-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0010_avaliacao_data_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_consulta']},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='observacoes_avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
