# Generated by Django 5.2.5 on 2025-08-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0011_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='observacoes_avaliacao',
            new_name='observacao_avaliacao',
        ),
    ]
